services:
  - type: web
    name: pathfinding-visualizer
    runtime: docker
    dockerfilePath: ./Dockerfile
    plan: free
    envVars:
      - key: PORT
        value: 8080
    healthCheckPath: /api/health
